# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbquery < Formula
  desc "Natural language SQL CLI for SQLite, Postgres, and MySQL"
  homepage "https://github.com/samyou/dbquery"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samyou/dbquery/releases/download/v0.1.0/dbquery_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "6892e1ac7be9dad10c149ee5a57f14e0c6146e87025e21bee2013b870a94003f"

      define_method(:install) do
        bin.install "dbquery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samyou/dbquery/releases/download/v0.1.0/dbquery_0.1.0_Darwin_arm64.tar.gz"
      sha256 "f288b99483e68c9c5090dc656eddabfac6a3e962328d9f239630d6abb56ce8d8"

      define_method(:install) do
        bin.install "dbquery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samyou/dbquery/releases/download/v0.1.0/dbquery_0.1.0_Linux_x86_64.tar.gz"
      sha256 "3b2f24f952a959289cb41081b57ae3a065a106a9445056a2438f8197ce471019"
      define_method(:install) do
        bin.install "dbquery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samyou/dbquery/releases/download/v0.1.0/dbquery_0.1.0_Linux_arm64.tar.gz"
      sha256 "85fe139e7f8156c4a31d059dc959f5f90f360d4c4a72758f6b1815d2137ebad0"
      define_method(:install) do
        bin.install "dbquery"
      end
    end
  end

  test do
    system "#{bin}/dbquery", "--help"
  end
end
