# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nn < Formula
  desc "Quick terminal notes CLI with date-based markdown files"
  homepage "https://github.com/samyou/nn"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samyou/nn/releases/download/v0.1.1/nn_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "c897c24f07af32fcebba384be280f58ffd51dfc045bd6f40fada81c79b8b655d"

      define_method(:install) do
        bin.install "nn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samyou/nn/releases/download/v0.1.1/nn_0.1.1_Darwin_arm64.tar.gz"
      sha256 "60de34ffd50264a272681c0ad95713621996e2208e3ca9719b73e0eac5230c81"

      define_method(:install) do
        bin.install "nn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samyou/nn/releases/download/v0.1.1/nn_0.1.1_Linux_x86_64.tar.gz"
      sha256 "4fe3718ce65bf67252c0d70887a7dac80503c461a62822a7aeb2d41b90c02801"
      define_method(:install) do
        bin.install "nn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samyou/nn/releases/download/v0.1.1/nn_0.1.1_Linux_arm64.tar.gz"
      sha256 "807504707b511f9f12bd8f833bc9faa4c2fd05c32c3b00018cd964d66ee67ef6"
      define_method(:install) do
        bin.install "nn"
      end
    end
  end

  test do
    system "#{bin}/nn", "--help"
  end
end
