# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nn < Formula
  desc "Quick terminal notes CLI with date-based markdown files"
  homepage "https://github.com/samyou/nn"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samyou/nn/releases/download/v0.1.2/nn_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "946abf3c500bea6e99e5f3158959c3b91530b6dc3a9b041e5694f86f51beac48"

      define_method(:install) do
        bin.install "nn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samyou/nn/releases/download/v0.1.2/nn_0.1.2_Darwin_arm64.tar.gz"
      sha256 "f36290228565af3937a443627c1b991e23104b2603dc3a4575c1c0f8dd620ccd"

      define_method(:install) do
        bin.install "nn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samyou/nn/releases/download/v0.1.2/nn_0.1.2_Linux_x86_64.tar.gz"
      sha256 "bc8a71e26ee0bca6d2c8c73c46e678173597ddb2a8b98b71539b99b08e32882f"
      define_method(:install) do
        bin.install "nn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samyou/nn/releases/download/v0.1.2/nn_0.1.2_Linux_arm64.tar.gz"
      sha256 "fb3857d7dd0d498e0c75024e264cb56afc33d268aa52c238d0a823bda3ca1dde"
      define_method(:install) do
        bin.install "nn"
      end
    end
  end

  test do
    system "#{bin}/nn", "--help"
  end
end
